In [2]:
import numpy as np
import random
from game import Game, Move, Player
import math

In [4]:
test_board1 = np.array([[0,1,0,0,0],
              [0,-1,-1,-1,1],
              [1,-1,0,-1,0],
              [0,-1,-1,1,1],
              [1,1,0,1,1]])
test_board2 = np.array([[0,1,0,1,0],
              [1,-1,-1,-1,0],
              [1,-1,0,-1,1],
              [1,-1,-1,1,1],
              [0,1,0,1,0]])
test_board3 = np.array([[0,0,1,1,1],
              [0,-1,-1,-1,0],
              [0,-1,0,-1,0],
              [1,-1,-1,1,1],
              [0,0,1,1,1]])

In [25]:
def get_legal_moves(board: np.ndarray, player_id: int):    
    SIDES = [(1,0), (2,0), (3,0), (4,0),
            (1,4), (2,4), (3,4), (4,4),
            (0,1), (0,2), (0,3), (0,4),
            (4,1), (4,2), (4,3), (0,0)]

    MOVES = [Move.TOP,
            Move.LEFT,
            Move.BOTTOM,
            Move.RIGHT]

    legal_moves = []

    for x, y in SIDES:
        if board[y,x] == player_id or board[y,x] == -1:
            moves = MOVES.copy()
            if x == 4:
                moves.remove(Move.RIGHT)
            if x == 0:
                moves.remove(Move.LEFT)
            if y == 4:
                moves.remove(Move.BOTTOM)
            if y == 0:
                moves.remove(Move.TOP)

            legal_moves.extend([((x,y), m) for m in moves])
            
    return legal_moves

[[ 0  1  0  0  0]
 [ 0 -1 -1 -1  1]
 [ 1 -1  0 -1  0]
 [ 0 -1 -1  1  1]
 [ 1  1  0  1  1]]


[((2, 0), <Move.LEFT: 2>),
 ((2, 0), <Move.BOTTOM: 1>),
 ((2, 0), <Move.RIGHT: 3>),
 ((3, 0), <Move.LEFT: 2>),
 ((3, 0), <Move.BOTTOM: 1>),
 ((3, 0), <Move.RIGHT: 3>),
 ((4, 0), <Move.LEFT: 2>),
 ((4, 0), <Move.BOTTOM: 1>),
 ((2, 4), <Move.TOP: 0>),
 ((2, 4), <Move.LEFT: 2>),
 ((2, 4), <Move.RIGHT: 3>),
 ((0, 1), <Move.TOP: 0>),
 ((0, 1), <Move.BOTTOM: 1>),
 ((0, 1), <Move.RIGHT: 3>),
 ((0, 3), <Move.TOP: 0>),
 ((0, 3), <Move.BOTTOM: 1>),
 ((0, 3), <Move.RIGHT: 3>),
 ((4, 2), <Move.TOP: 0>),
 ((4, 2), <Move.LEFT: 2>),
 ((4, 2), <Move.BOTTOM: 1>),
 ((0, 0), <Move.BOTTOM: 1>),
 ((0, 0), <Move.RIGHT: 3>)]

In [ ]:
def _get_legal_moves(self, board: np.ndarray):
        moves = list()
        rows, cols = board.shape
        for i in range(rows):
            if (board[i, 0] == -1):
                #print("match 1")
                pickable_piece = (0,i)
                if (i == 0):
                    insertions = (Move.BOTTOM, Move.RIGHT)
                elif (i == 4):
                    insertions = (Move.TOP, Move.RIGHT)
                else:
                    insertions = (Move.TOP, Move.BOTTOM, Move.RIGHT)
                
                for insertion in insertions:
                    #print((pickable_piece, insertion))
                    moves.append((pickable_piece, insertion))
            
            if (board[i, 4] == -1):
                #print("match 2")
                pickable_piece = (4,i)
                if (i == 0):
                    insertions = (Move.BOTTOM, Move.LEFT)
                elif (i == 4):
                    insertions = [Move.TOP, Move.LEFT]
                else:
                    insertions = (Move.TOP, Move.BOTTOM, Move.LEFT)
                for insertion in insertions:
                    #print((pickable_piece, insertion))
                    moves.append((pickable_piece, insertion))
        for j in range(cols):
            if(board[0, j] == self.player_id or board[0, j] == -1):
                #print("match 3")
                pickable_piece = (j,0)
                if(j == 0):
                    insertions = (Move.BOTTOM, Move.RIGHT)
                elif (j == 4):
                    insertions = (Move.BOTTOM, Move.LEFT)
                else:
                    insertions = (Move.LEFT, Move.RIGHT, Move.BOTTOM)
                for insertion in insertions:
                    #print((pickable_piece, insertion))
                    moves.append((pickable_piece, insertion))
            if(board[4, j] == self.player_id or board[4, j] == -1):
                #print("match 4")
                pickable_piece = (j,4)
                if (j == 0):
                    insertions = (Move.TOP, Move.RIGHT)
                elif (j == 4):
                    insertions = (Move.TOP, Move.LEFT)
                else:
                    insertions = (Move.LEFT, Move.RIGHT, Move.TOP)
                for insertion in insertions:
                    #print((pickable_piece, insertion))
                    moves.append((pickable_piece, insertion))
        random.shuffle(moves)
        return moves